apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamyard-clone-api
  labels:
    app: streamyard-clone-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamyard-clone-api
  template:
    metadata:
      labels:
        app: streamyard-clone-api
    spec:
      imagePullSecrets:
      - name: docker-login-secret
      containers:
      - name: streamyard-clone-api
        image: clintmathews/streamyard-clone-api:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
